version: '3'

services:
  minio:
    image: quay.io/minio/minio:latest
    platform: linux/arm64
    container_name: minio-server
    ports:
      - '9000:9000'
      - '9090:9090'
    environment:
      MINIO_ROOT_USER: miniousername
      MINIO_ROOT_PASSWORD: miniopassword
    volumes:
      - ./minio_data:/data
    command: server /data --console-address ":9090"
  
  spark-master:
    image: bitnami/spark:3.5.0
    container_name: spark-master
    environment:
      SPARK_MODE: master
      SPARK_MASTER_WEBUI_PORT: 9080
      SPARK_MASTER_PORT: 7077
    ports:
      - "9080:9080"
      - "7077:7077"
    deploy:
      resources:
        limits:
          memory: 2G

  spark-worker:
    image: bitnami/spark:3.5.0
    container_name: spark-worker
    environment:
      SPARK_MODE: worker
      SPARK_WORKER_WEBUI_PORT: 8081
      SPARK_WORKER_MEMORY: 3G
      SPARK_WORKER_CORES: 2
      SPARK_MASTER_URL: spark://spark-master:7077
    depends_on:
      - spark-master

  etl:
    build:
      context: .
      dockerfile: Dockerfile.etl
    container_name: etl
    environment:
      - PYTHONUNBUFFERED=1
    depends_on:
      - minio
      - spark-master 
      - spark-worker